In [1]:
import pandas as pd

In [3]:
df = pd.read_json("../data/initial_runs/initial_runs_combined.jsonl", lines=True)
df

,document,doc_id,general,specific,rewrite,similarity
0,VCC has announced a 3mm diffused LED indicator...,<urn:uuid:6df72631-bde9-4da6-ac74-dcbdb3208046>,"[Press Release, Formal Tone, Electronics Indus...","[L63 Series, 3mm Diffused LED, Robust Body, Ro...",[FOR IMMEDIATE RELEASE\n\nWe are pleased to an...,0.8899
1,· All children are expected to arrive at schoo...,<urn:uuid:e1449a11-cbd2-421e-86a2-21447de490ca>,"[School Policy, Dress Code, Uniform Guidelines...","[Grey Shorts Or Trousers, Navy Sweatshirt With...",[Our school is committed to maintaining a prof...,0.8727
2,A Hickory Construction Project\nFulton Lane Ba...,<urn:uuid:0c98e9e6-112b-4a46-9a79-041c53fefb46>,"[Construction Project, International Collabora...","[Hickory Construction, Fulton Lane, SP Setia D...","[In the heart of Melbourne, on Franklin Street...",0.8591
3,Jason Bourne: As a Queens native who were some...,<urn:uuid:ed491156-c732-4f10-aacd-10a9acc54758>,"[interview format, Hip Hop theme, conversation...","[Queens native, Nas inspiration, 50 Cent influ...","[As a Queens native, I've always been inspired...",0.6994
4,Mercury in western North America: A synthesis ...,<urn:uuid:499f14a2-d36b-4dd6-98cb-d6632ebc6268>,"[Environmental Study, Scientific Research, Reg...","[Western North America Region, Mercury Contami...",[This synthesis report presents an environment...,0.9165
...,...,...,...,...,...,...
39995,The law of sacrifice states that something of ...,<urn:uuid:0dc9f90a-61fe-4d42-98fa-4f8ad43e7d4f>,"[informal tone, reflective mood, personal narr...","[law of sacrifice concept, reassigning values,...",[As I sit here reflecting on my life's journey...,0.8333
39996,Non-Farm Payrolls remain on a positive run wit...,<urn:uuid:ecf1c3b8-9408-49f6-8baf-5f95751269b3>,"[economic context, labour market analysis, job...","[non-farm payrolls, private sector jobs growth...",[The labour market has shown strong job gains ...,0.8293
39997,MSU likely to pit Darien Harris against star t...,<urn:uuid:fab8354b-4eec-423a-8fa6-0e99a9d5b967>,"[sports reporting, football preview, analytica...","[Darien Harris, Jake Butt, Michigan State, Mic...",[This Saturday's highly anticipated rivalry ga...,0.8787
39998,At Expert Air Care Duct Cleaning & Dryer Vent ...,<urn:uuid:3505bbb0-8404-4937-bc16-9c46ce10bb7f>,"[customer-focused, informative tone, service-o...",[Expert Air Care Duct Cleaning & Dryer Vent Cl...,[At Expert Air Care Duct Cleaning & Dryer Vent...,0.9565
39999,Update: Jan 12:\nCBC: Tim Hortons says the lat...,<urn:uuid:b6cebde8-e1b3-4f0b-bd69-e1267537c7eb>,"[informal tone, conversational style, sarcasti...","[Tim Hortons, price hike controversy, GWNFA, N...",[Let's grab a double-double and talk about the...,0.8073

In [4]:
df.similarity.mean()

np.float64(0.846744845)

In [8]:
low_sim_df = df[df["similarity"] <= 0.7]
high_sim_df = df[df["similarity"] > 0.7]
low_sim_df

,document,doc_id,general,specific,rewrite,similarity
3,Jason Bourne: As a Queens native who were some...,<urn:uuid:ed491156-c732-4f10-aacd-10a9acc54758>,"[interview format, Hip Hop theme, conversation...","[Queens native, Nas inspiration, 50 Cent influ...","[As a Queens native, I've always been inspired...",0.6994
25,"President Frederic Will, BA, Ph.D.\nVice Presi...",<urn:uuid:33e5dee2-89d4-4dbd-a275-91c2156cdb2d>,"[Academic setting, Formal tone, Professional b...","[Faculty member names, University affiliations...",[The faculty at our institution comprises este...,0.6510
68,Check Free money for taking surveys in Danbury...,<urn:uuid:b50d3f85-465d-44e1-818a-9375c3d88df6>,"[informal tone, online opportunities, entrepre...","[taking surveys for money, watching videos for...",[Unlocking the secrets to financial freedom th...,0.5855
86,A yes answer to this question is not necessari...,<urn:uuid:ee0f0da2-29bd-4e24-895a-39a717e33b93>,"[informal tone, business context, optimistic o...","[rhetorical inquiry, emotive symbols, hyperlin...",[Are you ready to revolutionize your business ...,0.5972
104,The National Retail Federation spent weeks urg...,<urn:uuid:c6e6a2d9-694b-4e4e-9090-3737de73f9ef>,"[formal tone, informative style, political con...","[State of the Union address, retail jobs, dome...","[My fellow Americans, tonight I stand before y...",0.6349
...,...,...,...,...,...,...
39844,"| ""They can't keep this level of content up fo...",<urn:uuid:2a26a459-cedf-4ef8-8bf2-30c6d3c6ca83>,"[video game information, level description, pl...","[stage number, world name, previous stage, nex...","[In the platformer video game, Stage 5 is set ...",0.5471
39893,Guild: Steel Alliance\nLevel: 127.51 (Rank 50)...,<urn:uuid:f2022509-bf3a-45c6-adf2-f8308f0a9278>,"[gaming context, informative tone, formal lang...","[guild name, level indicator, rank display, ac...","[In the realm of ""Eternal Conquest"", a renowne...",0.6812
39917,... because Joy recommended it\n2) During thos...,<urn:uuid:f1d8d4ee-331b-40b0-8226-dc7d9720f04a>,"[conversational tone, informal style, cultural...","[Beatles history, 1960s music scene, film refe...","[So, have you ever wondered what it was like g...",0.6708
39958,Book title: Flipped\nAuthor: Wendelin Van Draa...,<urn:uuid:6b54ded1-082e-4336-946f-9aa1e57f1a38>,"[Informal Tone, Conversational Style, Personal...","[Young Adult Genre, Romance Novel Classificati...",[I just can't get enough of those swoony teen ...,0.6670
39981,"LUCKNOW, India (Reuters) - Thousands of youngs...",<urn:uuid:29e93a41-853a-42a3-b642-a8f0b2bf168a>,"[news article, informative tone, formal langua...","[Lucknow setting, train coach burning, rail tr...","[In Lucknow, a recent surge in youth unrest ha...",0.6986

In [11]:
low_sim_1_hot = pd.DataFrame(low_sim_df['general'].tolist()).stack().str.get_dummies().groupby(level=0).sum()
low_sim_1_hot.sum(axis=0)

 Aberth-Ehrlich Method       1
 Adamax                      1
 Amusing Content             1
 Big Data Analytics          1
 Brent’s Method              2
                            ..
youthful viewpoint           1
zero tax rate mention        1
zoological classification    1
zoological discussion        1
zoom adjustment warning      1
Length: 8878, dtype: int64

In [6]:
# Extract the "general" column and apply one-hot encoding
general_df = pd.DataFrame(df['general'].tolist()).stack().str.get_dummies().groupby(level=0).sum()

    DIY approach   Earn Cash Back program introduction   Formal Tone  \
0              0                                     0             0
1              0                                     0             0
2              0                                     0             0
3              0                                     0             0
4              0                                     0             0

    Formal language   Objective Style   athlete's mindset  \
0                 0                 0                   0
1                 0                 0                   0
2                 0                 0                   0
3                 0                 0                   0
4                 0                 0                   0

    automotive passion   career development   compositional challenge  \
0                    0                    0                         0
1                    0                    0                         0
2                    0                    0                         0
3                    0                    0                         0
4                    0                    0                         0

    customer service  ...  youthful protagonist  youthful subject  \
0                  0  ...                     0                 0
1                  0  ...                     0                 0
2                  0  ...                     0                 0
3                  0  ...                     0                 0
4                  0  ...                     0                 0

   youthful tone  youthful vibe  zero tolerance policy  zip file recovery  \
0              0              0                      0                  0
1              0              0                      0                  0
2              0              0                      0                  0
3              0              0                      0                  0
4              0              0                      0                  0

   zoned layout  zoning decisions  zoo event  zoology context
0             0                 0          0                0
1             0                 0          0                0
2             0                 0          0                0
3             0                 0          0                0
4             0                 0          0                0

[5 rows x 8023 columns]

In [7]:
general_df

,DIY approach,Earn Cash Back program introduction,Formal Tone,Formal language,Objective Style,athlete's mindset,automotive passion,career development,compositional challenge,customer service,...,youthful protagonist,youthful subject,youthful tone,youthful vibe,zero tolerance policy,zip file recovery,zoned layout,zoning decisions,zoo event,zoology context
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [1]:
import pandas as pd
import json

# Load the JSONL file into a pandas DataFrame
file_path = '/home/otto-tarkka/Documents/work/LLM_document_descriptors/data/initial_runs/initial_runs_combined.jsonl'
data = []
with open(file_path, 'r') as file:
    for line in file:
        data.append(json.loads(line))

df = pd.DataFrame(data)

# Ensure that the "general" column does not contain empty lists
df['general'] = df['general'].apply(lambda x: x if isinstance(x, list) and len(x) > 0 else ['empty'])

# Extract the "general" column and apply one-hot encoding
general_df = pd.DataFrame(df['general'].tolist()).stack().str.get_dummies().groupby(level=0).sum()

general_df

MemoryError: Unable to allocate 585. GiB for an array with shape (522393, 150228) and data type int64

In [41]:
# Calculate the sum of each row in the general_df DataFrame
general_df.sum(axis=1).value_counts()

6      100
10      84
7       78
8       72
15      68
9       64
5       64
14      57
11      56
12      51
16      49
13      46
17      41
18      32
19      23
20      17
21      15
22      12
23      11
25       8
28       8
24       8
27       5
30       4
29       3
26       3
47       3
34       2
44       2
31       2
36       2
54       2
46       1
37       1
32       1
134      1
3        1
72       1
33       1
43       1
Name: count, dtype: int64

In [48]:
# Apply MCA to the general_df DataFrame
from prince import MCA

mca = MCA(
    n_components=100,
    n_iter=3,
    copy=True,
    check_input=True,
    engine='sklearn',
    random_state=42,
    one_hot=False # Set to True if the input data is not already one-hot encoded
)

mca = mca.fit(general_df)

mca.eigenvalues_summary

          eigenvalue % of variance % of variance (cumulative)
component
0              0.964         0.16%                      0.16%
1              0.961         0.16%                      0.32%
2              0.958         0.16%                      0.48%
3              0.955         0.16%                      0.64%
4              0.951         0.16%                      0.79%
...              ...           ...                        ...
95             0.777         0.13%                     13.80%
96             0.776         0.13%                     13.93%
97             0.772         0.13%                     14.05%
98             0.771         0.13%                     14.18%
99             0.769         0.13%                     14.31%

[100 rows x 3 columns]